WebAppPatients/WebAppPatients/Models/DetailsPatient.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebAppPatients.Models
{
    public class DetailsPatient
    {
        public Patients Patient { get; set; }
        public IEnumerable<Prescriptions> Prescriptions { get; set; }
        public Dictionary<Prescriptions, List<Medicaments>> PrescriptionMedicamentsDict { get; set; }

        public DetailsPatient(Patients patient, IEnumerable<Prescriptions> prescriptions, Dictionary<Prescriptions, List<Medicaments>> prescriptionMedicamentsDict)
        {
            Patient = patient;
            Prescriptions = prescriptions;
            PrescriptionMedicamentsDict = prescriptionMedicamentsDict;
        }
    }
}

WebAppPatients/WebAppPatients/Models/Doctors.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebAppPatients.Models
{
    public partial class Doctors
    {
        public Doctors()
        {
            Prescriptions = new HashSet<Prescriptions>();
        }

        public int IdDoctor { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }

        public virtual ICollection<Prescriptions> Prescriptions { get; set; }
    }
}

WebAppPatients/WebAppPatients/Models/Medicaments.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebAppPatients.Models
{
    public class Medicaments
    {
        public Medicaments()
        {
            PrescriptionMedicament = new HashSet<PrescriptionMedicament>();
        }

        public int IdMedicament { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public virtual ICollection<PrescriptionMedicament> PrescriptionMedicament { get; set; }
    }
}

WebAppPatients/WebAppPatients/Models/Patients.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace WebAppPatients.Models
{
    public class Patients
    {
        public Patients()
        {
            Prescriptions = new HashSet<Prescriptions>();
        }

        public int IdPatient { get; set; }
        [DisplayName("Imię")]public string FirstName { get; set; }
        [DisplayName("Nazwisko")]public string LastName { get; set; }
        [DisplayName("Data urodzenia")]public DateTime Birthdate { get; set; }
        public virtual ICollection<Prescriptions> Prescriptions { get; set; }
    }
}

WebAppPatients/WebAppPatients/Models/PersonsDbContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace WebAppPatients.Models
{
    public partial class PersonsDbContext : DbContext
    {
        public PersonsDbContext()
        {
        }

        public PersonsDbContext(DbContextOptions<PersonsDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Doctors> Doctors { get; set; }
        public virtual DbSet<Medicaments> Medicaments { get; set; }
        public virtual DbSet<Patients> Patients { get; set; }
        public virtual DbSet<PrescriptionMedicament> PrescriptionMedicament { get; set; }
        public virtual DbSet<Prescriptions> Prescriptions { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Doctors>(entity =>
            {
                entity.HasKey(x => x.IdDoctor);

                entity.Property(e => e.FirstName).IsRequired();

                entity.Property(e => e.LastName).IsRequired();
            });

            modelBuilder.Entity<Medicaments>(entity =>
            {
                entity.HasKey(x => x.IdMedicament);

                entity.Property(e => e.Description).IsRequired();

                entity.Property(e => e.Name).IsRequired();

                entity.Property(e => e.Type).IsRequired();
            });

            modelBuilder.Entity<Patients>(entity =>
            {
                entity.HasKey(x => x.IdPatient);

                entity.Property(e => e.FirstName).IsRequired();

                entity.Property(e => e.LastName).IsRequired();
            });

            modelBuilder.Entity<PrescriptionMedicament>(entity =>
            {
                entity.HasKey(x => new { x.IdMedicament, x.IdPrescription });

                entity.ToTable("Prescription_Medicament");

                entity.HasIndex(x => x.IdPrescription);

                entity.Property(e => e.Details).IsRequired();

                entity.HasOne(d => d.IdMedicamentNavigation)
                    .WithMany(p => p.PrescriptionMedicament)
                    .HasForeignKey(x => x.IdMedicament);

                entity.HasOne(d => d.IdPrescriptionNavigation)
                    .WithMany(p => p.PrescriptionMedicament)
                    .HasForeignKey(x => x.IdPrescription);
            });

            modelBuilder.Entity<Prescriptions>(entity =>
            {
                entity.HasKey(x => x.IdPrescription);

                entity.HasIndex(x => x.IdDoctor);

                entity.HasIndex(x => x.IdPatient);

                entity.HasOne(d => d.IdDoctorNavigation)
                    .WithMany(p => p.Prescriptions)
                    .HasForeignKey(x => x.IdDoctor);

                entity.HasOne(d => d.IdPatientNavigation)
                    .WithMany(p => p.Prescriptions)
                    .HasForeignKey(x => x.IdPatient);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}

WebAppPatients/WebAppPatients/Models/PrescriptionMedicament.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebAppPatients.Models
{
    public partial class PrescriptionMedicament
    {
        public int IdPrescription { get; set; }
        public int IdMedicament { get; set; }
        public int Dose { get; set; }
        public string Details { get; set; }
        public virtual Medicaments IdMedicamentNavigation { get; set; }
        public virtual Prescriptions IdPrescriptionNavigation { get; set; }
    }
}

WebAppPatients/WebAppPatients/Models/Prescriptions.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace WebAppPatients.Models
{
    public partial class Prescriptions
    {
    
        public int IdPrescription { get; set; }
        public int Date { get; set; }
        public int DueDate { get; set; }
        public int IdPatient { get; set; }
        public int IdDoctor { get; set; }
        public virtual Doctors IdDoctorNavigation { get; set; }
        public virtual Patients IdPatientNavigation { get; set; }
        public virtual ICollection<PrescriptionMedicament> PrescriptionMedicament { get; set; }
    }
}

WebAppPatients/WebAppPatients/Controllers/PatientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebAppPatients.Models;
using WebAppPatients.Services;

namespace WebAppPatients.Controllers
{
    public class PatientsController : Controller
    {
        private readonly IServiceDb _service;

        public PatientsController(IServiceDb service)
        {
            _service = service;
        }

        public IActionResult GetPatients()
        {
            return View (_service.GetPatients());
        }

        public IActionResult GetPatientDetails(int index)
        {
            return View(_service.GetPatientDetails(index));
        }

        [HttpPost]
        public IActionResult AddPatient(Patients patient)
        {
            _service.AddPatient(patient);
            return RedirectToAction("GetPatients");
        }

        public IActionResult RemovePatient(int index)
        {
            _service.RemovePatient(index);
            return RedirectToAction("GetPatients");
        }
    }
}

WebAppPatients/WebAppPatients/Views/Patients/GetPatientDetails.cshtml
@model WebAppPatients.Models.DetailsPatient

<h3>Dane Pacjenta</h3>

<p>
    <table>
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(modelItem => modelItem.Patient.FirstName)</th>
                <th>@Html.DisplayNameFor(modelItem => modelItem.Patient.LastName)</th>
                <th>@Html.DisplayNameFor(modelItem => modelItem.Patient.Birthdate)</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Model.Patient.FirstName</td>
                <td>@Model.Patient.LastName</td>
                <td>@Model.Patient.Birthdate</td>
            </tr>
        </tbody>
    </table>

    <h4>Lista recept</h4>
    <table>
        <thead>
            <tr>
                <th>Data wystawienia</th>
                <th>Data przedawnienia</th>
                <th>Numer doktora</th>
                <th>Lista leków</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var presc in Model.Prescriptions)
            {
                <tr>
                    <td>@presc.Date</td>
                    <td>@presc.DueDate</td>
                    <td>@presc.IdDoctor</td>
                    <td>
                        @foreach (var med in Model.PrescriptionMedicamentsDict[presc])
                        {
                            @med.Name
                            <br />
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <br />
    @Html.ActionLink("Wróć do listy pacjentów", "GetPatients", "Patients", new { }, new { @class = "homeBtn" })

</p>

WebAppPatients/WebAppPatients/Views/Patients/GetPatients.cshtml
@model IEnumerable<WebAppPatients.Models.Patients>

<h3>Lista Pacjentów</h3>

<p>
    <table>
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(modelItem => modelItem.FirstName)</th>
                <th>@Html.DisplayNameFor(modelItem => modelItem.LastName)</th>
                <th>@Html.DisplayNameFor(modelItem => modelItem.Birthdate)</th>
                <th>Opcje</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var patient in Model)
            {
                <tr>
                    <td>@patient.FirstName</td>
                    <td>@patient.LastName</td>
                    <td>@patient.Birthdate</td>
                    <td class="buttonTd">
                        @Html.ActionLink("Detale pacjenta", "GetPatientDetails", "Patients", new { index = patient.IdPatient }, new { @class = "homeBtn" })
                        <br />
                        @Html.ActionLink("Usuń pacjenta", "RemovePatient", "Patients", new { index = patient.IdPatient }, new { @class = "homeBtn" })
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <h3>Dodawanie Pacjenta</h3>
    <table>
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(modelItem => modelItem.FirstName)</th>
                <th>@Html.DisplayNameFor(modelItem => modelItem.LastName)</th>
                <th>@Html.DisplayNameFor(modelItem => modelItem.Birthdate)</th>
                <th>Opcje</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td>
                    @Html.ActionLink("Dodaj pacjenta", "AddPatient", "Patients", new { }, new { @class = "homeBtn" })
                </td>
            </tr>
        </tbody>
    </table>
    <br />
</p>

WebAppPatients/WebAppPatients/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Pacjenci</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="css/myStyle.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        @RenderBody()
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</body>
</html>